version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - SECRET_KEY=clave_secreta_desarrollo_local_2024
      - JWT_SECRET_KEY=jwt_secret_key_desarrollo_local_2024
      - DATABASE_URL=sqlite:///inventario.db
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001
    volumes:
      - ./instance:/app/instance
      - ./app:/app/app
    restart: unless-stopped 