[build]
  base = "frontend"
  publish = "build"
  command = "npm run build"

# Redirecciones actualizadas para apuntar a Railway (dominio temporal)
[[redirects]]
  from = "/api/*"
  to = "https://sistemadesplegableboo-production.up.railway.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/inventario/*"
  to = "https://sistemadesplegableboo-production.up.railway.app/inventario/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/usuarios/*"
  to = "https://sistemadesplegableboo-production.up.railway.app/usuarios/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/tickets/*"
  to = "https://sistemadesplegableboo-production.up.railway.app/tickets/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/documentos/*"
  to = "https://sistemadesplegableboo-production.up.railway.app/documentos/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/bitacoras/*"
  to = "https://sistemadesplegableboo-production.up.railway.app/bitacoras/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/trabajos/*"
  to = "https://sistemadesplegableboo-production.up.railway.app/trabajos/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ubicaciones/*"
  to = "https://sistemadesplegableboo-production.up.railway.app/ubicaciones/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/categorias/*"
  to = "https://sistemadesplegableboo-production.up.railway.app/categorias/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/avisos/*"
  to = "https://sistemadesplegableboo-production.up.railway.app/avisos/:splat"
  status = 200
  force = true
