[build]
  base = "frontend"
  publish = "build"
  command = "npm run build"

# Redirecciones actualizadas para apuntar a Railway
[[redirects]]
  from = "/api/*"
  to = "https://api.soporteches.online/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/inventario/*"
  to = "https://api.soporteches.online/inventario/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/usuarios/*"
  to = "https://api.soporteches.online/usuarios/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/tickets/*"
  to = "https://api.soporteches.online/tickets/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/documentos/*"
  to = "https://api.soporteches.online/documentos/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/bitacoras/*"
  to = "https://api.soporteches.online/bitacoras/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/trabajos/*"
  to = "https://api.soporteches.online/trabajos/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ubicaciones/*"
  to = "https://api.soporteches.online/ubicaciones/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/categorias/*"
  to = "https://api.soporteches.online/categorias/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/avisos/*"
  to = "https://api.soporteches.online/avisos/:splat"
  status = 200
  force = true
