# Render Blueprint YAML para Flask backend
services:
  - type: web
    name: flask-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        sync: false
    autoDeploy: true
    healthCheckPath: "/"
# Si usas base de datos externa, configura DATABASE_URL aquí
# Si quieres agregar el frontend como servicio estático, puedes agregar otro bloque de tipo static_site
